import { Header } from '@/components/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import { Footer } from '@/components/Footer'

const inter = Inter({ subsets: ['latin', 'cyrillic'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + ' ' + 'flex flex-col justify-between items-center min-h-screen'}>
        <Header />
        <main className='flex flex-grow flex-col items-center justify-start w-full'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
