import './globals.css'
import { inter, poppins } from './fonts'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${inter.variable} font-sans`}>
        <div className='flex flex-col justify-between items-center min-h-screen'>
          {children}
        </div>
      </body>
    </html>
  )
}
